# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3cdc82e9e301eb7812d6505bfdb2ed85724d9aa309b9c3fa89d87880368913e8aade723b1c20066562ddd2165c963969a13190bd3a4a27642bb5294e3d5fb33

test:
  secret_key_base: 4cf68386a1947ca50cd53f51a19fa1fd844e5d100146701b46ac660dc0936da512d740c701f95173147aca1666af8c5480327ce136307da614ea6894b882105c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
